### PR TITLE
pin redis and rabbitmq needs privileged: true

### PR DESCRIPTION
**Pull request by guzzijones**
rabbitmq is not starting.  redis is not starting

### CODE REVIEW

**Comment by guzzijones** [comment]
```
+ case "$1" in
+ echo Starting Packages Build for bionic ...
Starting Packages Build for bionic ...
+ docker-compose -f docker-compose.circle2.yml -f docker-compose.override.yml up redis
Creating st2-packages_redis_1 ... 
Creating st2-packages_redis_1 ... doneAttaching to st2-packages_redis_1
redis_1             | 1:C 24 Jul 2023 00:18:39.124 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1             | 1:C 24 Jul 2023 00:18:39.124 # Redis version=6.0.20, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1             | 1:C 24 Jul 2023 00:18:39.124 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1             | 1:M 24 Jul 2023 00:18:39.125 * Running mode=standalone, port=6379.
redis_1             | 1:M 24 Jul 2023 00:18:39.125 # Server initialized
redis_1             | 1:M 24 Jul 2023 00:18:39.125 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1             | 1:M 24 Jul 2023 00:18:39.125 # Fatal: Can't initialize Background Jobs
```

**Comment by guzzijones** [comment]
```
+ docker-compose -f docker-compose.circle2.yml -f docker-compose.override.yml up rabbitmq
Creating st2-packages_rabbitmq_1 ... 
Creating st2-packages_rabbitmq_1 ... doneAttaching to st2-packages_rabbitmq_1
rabbitmq_1          | Failed to create thread: Operation not permitted (1)
rabbitmq_1          | Aborted (core dumped)
st2-packages_rabbitmq_1 exited with code 0
+ docker-compose -f docker-compose.circle2.yml 
```

**Comment by guzzijones** [comment]
```
+ case "$1" in
+ echo Starting Packages Build for bionic ...
Starting Packages Build for bionic ...
+ free -hm
               total        used        free      shared  buff/cache   available
Mem:            15Gi       395Mi       9.0Gi       0.0Ki       6.0Gi        14Gi
Swap:             0B          0B          0B
+ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         146G   13G  133G   9% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/root       146G   13G  133G   9% /etc/hosts
shm              48G     0   48G   0% /dev/shm
tmpfs            48G     0   48G   0% /mnt/ramdisk
tmpfs           1.6G  892K  1.6G   1% /run/docker.sock
tmpfs           7.7G     0  7.7G   0% /proc/acpi
tmpfs           7.7G     0  7.7G   0% /proc/scsi
tmpfs           7.7G     0  7.7G   0% /sys/firmware
```

**Comment by guzzijones** [comment]
looks like there are permission issues going on.  plenty of ram and disk

**Review by armab — APPROVED** [review]
Thanks for fixing the build! 👍

**Review by cognifloyd — APPROVED** [review]

**Pull request merged**
