### PR TITLE
Mistral client wrapper

### PR DESCRIPTION
**Pull request by armab**
Overrides `OS_MISTRAL_URL` to use `127.0.0.1` instead of `localhost` for mistral client via wrapper script, approach descried: https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.9

Related to issue #157

cc @lakshmi-kannan

### CODE REVIEW

**Comment by armab** [comment]
Reproducing your issue: 

```sh
echo '127.0.1.1 localhost' > /etc/hosts
```

This works OK now, since `127.0.0.1` is default for mistral client: 
```sh
root@ubuntu14:/home/vagrant# mistral execution-list
+--------+----------+-------------+-------------------+--------+------------+------------+------------+
| ID     | Workflow | Description | Task Execution ID | State  | State info | Created at | Updated at |
+--------+----------+-------------+-------------------+--------+------------+------------+------------+
| <none> | <none>   | <none>      | <none>            | <none> | <none>     | <none>     | <none>     |
+--------+----------+-------------+-------------------+--------+------------+------------+------------+
```

Overriding `127.0.0.1` -> `localhost` example: 
```sh
export OS_MISTRAL_URL=http://localhost:8989/v2

root@ubuntu14:/home/vagrant# mistral execution-list
ERROR (app) HTTPConnectionPool(host='localhost', port=8989): Max retries exceeded with url: /v2/executions?sort_keys=created_at&sort_dirs=asc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7214dd29d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by dennybaa** [comment]
So does it work? I think no... Wrapper script should the follow logic, imo...

1. if `OS_MISTRAL_URL` is not given, then should be set as `http://127.0.0.1:8989/v2`
2. if `OS_MISTRAL_URL` given, it should be used.
3. if `OS_MISTRAL_URL` contains localhost, then localhost should be overwritten to `127.0.0.1` (since our service listens there).

This logic handles wrapper scenario in more correct way, fix me if I'm wrong.

**Comment by armab** [comment]
It implements `1` and `2` from your list.

`3` I think is unexpected and agressive behavior. If you pass `OS_MISTRAL_URL` env variable explicitly (no matter what value) - it will be used. No string modification/replace is needed here, - you have full control over env variable.

**Comment by dennybaa** [comment]
yup. maybe it's an overkill indeed.

**Comment by lakshmi-kannan** [comment]
Me likey likey.

**Comment by armab** [comment]
That thing is in stable packages (after rebuild)

**Pull request merged**
