### PR TITLE
Fix outdated package lists during install script

### PR DESCRIPTION
**Pull request by m4dcoder**
The image has outdated package lists and causes install of dependencies to fail. Add update prior to install.

### CODE REVIEW

**Comment by Kami** [comment]
Nice, good catch! :+1:

**Comment by armab** [comment]
Despite the fact that this fast fix works, the real solution for the root cause is to update Docker environment, eg where packages are built.

Eg. the right way is to apply `upgrade` on Docker images, rebuild them, deploy to hub and idea is that build environment is always in the same state, aka immutable and doesn't depend on random version "upgrades". Upgrading packages on every build is also slower, comparing to fully pre-build Docker images.

See: https://hub.docker.com/r/stackstorm/packagingenv/tags/

**Comment by Kami** [comment]
Agreed, +1.

**Comment by armab** [comment]
I created an issue not to forget about upgrading original Docker Images: https://github.com/StackStorm/st2-packages/issues/343

**Pull request merged**
