### PR TITLE
Remove st2 resultstracker

### LINKED ISSUE #668: Remove the st2resultstracker service from packaging
As mistral is deprecated, remove st2resultstracker service from the packaging & startup logic.

See https://github.com/StackStorm/st2/issues/5070 for more context.

This should be easy & fun task, if anyone from @StackStorm/contributors wants to help removing that.

### PR DESCRIPTION
**Pull request by winem**
This PR removes all references to st2resultstracker in the package specs and service definitions as well as the corresponding service file.

closes #668

### CODE REVIEW

**Comment by winem** [comment]
The workflow fails because st2ctl still checks the state of the st2resultstracker and can't find it any more. 

See https://github.com/StackStorm/st2/blob/746ae505e77126af6b7473a91eb1e98614a67568/st2common/bin/st2ctl#L17

**Review by armab — APPROVED** [review]
Looks good, Thanks! :+1: 

Once the the CI is green (st2ctl) we're good to merge this.

**Comment by winem** [comment]
Now there is a circular dependency between this PR and https://github.com/StackStorm/st2/pull/5108 

Agreed with @blag to keep this PR as it is and merge both PRs on monday. The Exchange pack CI builds do have a higher priority and we want them to succeed over the weekend. 

See https://stackstorm-community.slack.com/archives/CSBELJ78A/p1608330230290400

**Review by armab — CHANGES_REQUESTED** [review]
The only issue I found based on https://github.com/StackStorm/st2/pull/5108 build is that Makefile still includes resulstracker and needs a change, see: https://github.com/StackStorm/st2-packages/blob/master/packages/st2/Makefile#L83-L84

**Review by armab — APPROVED** [review]
CI is happy now! :+1: 

Thanks for the contribution, merging.

**Comment by armab** [comment]
@winem Following this PR change, we'll need a fix in Ansible-st2 repository (https://github.com/stackstorm/ansible-st2) which started to fail because it included the `st2resultstracker` in the list of services.
Could you please submit a small PR for that?

**Pull request merged**
