### PR TITLE
WIP - Initial Debian Buster support

### PR DESCRIPTION
**Pull request by nzlosh**
Used consistent indentation in st2_bootstrap shell scripts.
Opted to use case instead of multiple logical comparators in a if condition (clearer to read).
Updated docker-compose files with Buster information.

### CODE REVIEW

**Comment by nzlosh** [comment]
This pull request is related to https://github.com/StackStorm/st2packaging-dockerfiles/pull/75

**Comment by punkrokk** [comment]
@nzlosh Safe to assume that you need the dockerfiles merged for this to build?

**Comment by nzlosh** [comment]
@punkrokk Yes, that's my understanding.  I built the images locally so they were available to build the Debian packages.  From what I gathered, `st2package-dockerfiles` needs to be built and pushed to quai.io before this pull request will run correctly.

**Comment by nzlosh** [comment]
Stale, closing.

**Pull request closed without merging**
