### PR TITLE
Fix nginx config getting compressed due to its filesize

### PR DESCRIPTION
**Pull request by enykeev**
Special thanks to Joey Hess for this wonderful journey :(

### CODE REVIEW

**Comment by dennybaa** [comment]
E_TOOMANY_REBASE please follow #205

**Comment by armab** [comment]
Just usual stuff in DevOps world :)
http://devopsreactions.tumblr.com/post/140266094325/when-you-fix-a-bug-that-youve-been-working-on-all

**Comment by Kami** [comment]
Good catch :+1:

**Comment by Kami** [comment]
And of course thanks for digging into this. This was definitely a very nasty and hard to track down bug.

**Pull request merged**
