### PR TITLE
removing apparently "FAR FUTURE PREOPTIMIZATION"

### PR DESCRIPTION
**Pull request by dennybaa**
concerns #90

### CODE REVIEW

**Comment by enykeev** [comment]
I'm personally against removing work that already have been done. Worse than that, we'll be breaking `git blame` so when we're going to bring this files back again, there will be no way to figure out who added specific line and why. And in this particular project it's especially important, there's just too much of "WAT?" moments. I'd say that if we are concerned of build time and amount of effort required to move this project forward, lets only focus on st2bundle\mistral and sync the rest later, but let the stuff stay.

**Comment by dzimine** [comment]
Let's go for it.

**Comment by dennybaa** [comment]
awesome @dzimine I totally agree, I will prepare probably new PR a bit later. And of course all the work we'll save in a feature branch.

**Comment by dzimine** [comment]
Please do sooner: once we share this with the world today, people will look and the less confusion the better.

**Comment by dennybaa** [comment]
@dzimine closed in favor #163

**Pull request closed without merging**
