### PR TITLE
Correct order for mistral commands

### PR DESCRIPTION
**Pull request by armab**
Try to fix mistral

https://stackstorm.slack.com/archives/packages/p1453939452000836
https://stackstorm.slack.com/archives/packages/p1453939787000852

Related to https://github.com/StackStorm/st2-packages/issues/113 and https://github.com/StackStorm/st2-packages/issues/119

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
Holy jolly!

**Comment by dennybaa** [comment]
@lakshmi-kannan @armab 
yup. the order was correct when used clean db. So it might be so that we don't have a clean db anymore.

I wonder if circle ci nodes (1,2,3..) use the same shared service containers such as postgres, rabbit and mongo?

**Comment by dennybaa** [comment]
if db is not clean and it is so. So also it's a mystery why it worked before with mistral started with one worker spawned with `mistral-server` (handled by eventlet.wsgi)... Hmm it's strange...

**Comment by dennybaa** [comment]
i've merged seems, order fixed the issue completely.

**Comment by armab** [comment]
> yup. the order was correct when used clean db.

No, as @m4dcoder the order should be *exactly*:
1) run all migrations
2) start mistral

**Comment by armab** [comment]
We couldn't merge this PR only because GitHub went down :/

**Pull request merged**
