### PR TITLE
Support u16 in install script

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by enykeev** [comment]
Packages published:
- [x] st2
- [x] st2mistral
- [x] st2web
- [x] st2flow
- [ ] st2chatops
- [ ] st2enterprise
- [ ] st2-enterprise-ldap-auth

Packages promoted to stable:
- [ ] st2
- [ ] st2mistral
- [ ] st2web
- [ ] st2flow
- [ ] st2chatops
- [ ] st2enterprise
- [ ] st2-enterprise-ldap-auth

Distributions tested in unstable:
- [ ] centos6
- [ ] centos7
- [ ] trusty
- [ ] xenial
- [ ] wheezy
- [ ] jessie

**Comment by lakshmi-kannan** [comment]
@enykeev +1 to merge. Related: https://github.com/StackStorm/st2-test-ground/pull/4

BTW I think we've to definitely address this comment - https://github.com/StackStorm/st2-packages/pull/326#discussion_r71686505 from @armab for sure. I can volunteer someone into making that change if you are sick of packaging :). Let me know. 

1. When do you think we should include CI for U16? https://github.com/StackStorm/st2ci/tree/master/rules
Someone else other than you would do it.

2. When (1) is done, community will get to play with it for a while. Then we can make U16 the default OS for our CI. Currently, merge commits to st2 master only trigger CI for U16. 

3. When (2) is done, we've to add release workflows for U16.

**Comment by enykeev** [comment]
> I think we've to definitely address this comment - #326 (comment)

I'll fix that by Monday.

> When do you think we should include CI for U16? https://github.com/StackStorm/st2ci/tree/master/rules

Sooner the better. I believe that all we need to do is to find a proper AMI, add it to kw store and add its name to enum.

**Comment by enykeev** [comment]
The changes had been independently merged in #348. Closing.

**Pull request closed without merging**
