### PR TITLE
Add redis to install scripts

### PR DESCRIPTION
**Pull request by m4dcoder**
The coordinator service is required in most cases for running workflows. Install redis-server and configure redis as the default coordinator backend used by tooz. This will avoid a number of workflow issues, especially for new StackStorm users.

### CODE REVIEW

**Comment by m4dcoder** [comment]
This PR pairs with https://github.com/StackStorm/st2/pull/5226.

**Comment by armab** [comment]
Looks good :+1: 


We'll also need to include Redis in CI, Tests and docker-compose:
* https://github.com/StackStorm/st2-packages/blob/master/docker-compose.override.yml
* https://github.com/StackStorm/st2-packages/blob/master/docker-compose.yml
* https://github.com/StackStorm/st2-packages/blob/master/docker-compose.circle2.yml
* https://github.com/StackStorm/st2-packages/blob/master/docker-compose.circle.yml
* https://github.com/StackStorm/st2-packages/blob/master/scripts/generate_st2_config.sh
* https://github.com/StackStorm/st2-packages/blob/master/rake/spec/default/60-st2_all-services-ok_spec.rb#L8-L11

**Comment by Kami** [comment]
As @armab said, LGTM< just need to make sure we update all other affected places (sadly there are quite a lot of those and some of those we will only stumble upon in the future - e.g. st2web also uses docker compose setup for end to end tests, etc.).

**Review by armab — APPROVED** [review]
Looks great with updating it in all the places! :+1: 
Additional thanks for adding CircleCI smoke tests here to run Redis in Docker.

---

We'll also need for `stackstorm/st2` to add the default Redis `[coordination]` string in the default `st2.conf`:
https://github.com/StackStorm/st2/blob/master/conf/st2.package.conf similar to other backends like Mongo and RabbitMQ.

**Pull request merged**
