### PR TITLE
[WIP] EL9 Package build

### PR DESCRIPTION
**Pull request by amanda11**
Work in progress on adding build of EL9 using rockylinux9 containers

### CODE REVIEW

**Comment by nzlosh** [comment]
@amanda11 What else is necessary for this PR to be merged?

**Comment by amanda11** [comment]
> @amanda11 What else is necessary for this PR to be merged?

The EL9 CircleCI to pass!!!!

It's got some odd problem about not finding virtualenv module, even though its installed. I have had this before on these containers (I think when adding in EL8) but not sure...

```
[package: st2] [15:30:45]      + virtualenv -p python3 --no-download /tmp/st2-20240129-8-glnosz/st2/build/BUILDROOT/st2-3.9dev-1.x86_64/opt/**********/st2
[package: st2] [15:30:45]      Traceback (most recent call last):
[package: st2] [15:30:45]        File "/usr/local/bin/virtualenv", line 5, in <module>
[package: st2] [15:30:45]          from virtualenv.__main__ import run_with_catch
[package: st2] [15:30:45]      ModuleNotFoundError: No module named 'virtualenv'
```

**Comment by amanda11** [comment]
Not at all - I may have some time this afternoon - but definitely glad for some help.
Feel free to push up to this PR any fixes etc.

**Comment by amanda11** [comment]
> Do you mind if I take a look this week to try and find out what's going on?

I have got passed that EL9 error now, just trying to get all 5 builds green...

**Comment by nzlosh** [comment]
I started working in another branch to avoid interfering with yours.  master has been merged into it.  There should be 4 builds.

**Comment by amanda11** [comment]
> I started working in another branch to avoid interfering with yours. master has been merged into it. There should be 4 builds. #742

OK - I just merged master, but I think I've got it working now - got it so that it passed on EL9, so just need to make sure the if/else/endif on the EL stuff is correct.

**Comment by amanda11** [comment]
Status: Use docker engine 19:03.14 - and all builds and tests pass except EL9 doesn't build
Using latest docker or docker 20 for remote engine -> all builds including EL9 pass, but tests are not able to start and connect to container.

**Pull request closed without merging**
