### PR TITLE
actionrunner as root:st2packs, packs reownership for upgrades compatibility

### PR DESCRIPTION
**Pull request by dennybaa**

### CODE REVIEW

**Comment by dzimine** [comment]
Unit tests needed for this?

**Comment by DoriftoShoes** [comment]
LGTM

**Comment by dennybaa** [comment]
@dzimine The package life-cycle validation tests are absent as a class, at the point we have no tests except those serverspec/rspec which are run on package build up. Of course those tests don't cover removal/upgrading case to validate that the process goes smooth.
However I've tested manually and forcibly anyone of us who'll be doing packages upgrade can notice bugs if there are any.

**Comment by dennybaa** [comment]
@DoriftoShoes awesome i'm going to merge, so we can finally have permissions story sorted out

**Pull request merged**
