### PR TITLE
bundle build only

### PR DESCRIPTION
**Pull request by dennybaa**

### CODE REVIEW

**Comment by armab** [comment]
Is `package_name` ENV variable I can pass from Circle to build only these 2 packages?

**Comment by armab** [comment]
Please also change `st2api` here to `st2bundle`: 
https://github.com/StackStorm/st2-packages/blob/master/.circle/buildenv.sh#L47

And if `st2bundle` and `mistral` just hardcoded - we're good to try the build.

**Comment by armab** [comment]
Let's try :+1:

**Comment by armab** [comment]
https://stackstorm.slack.com/archives/standup/p1453133448000706

**Comment by lakshmi-kannan** [comment]
:+1:

**Pull request merged**
