### PR TITLE
St2 only, rake refactored.

### PR DESCRIPTION
**Pull request by dennybaa**

### CODE REVIEW

**Comment by dennybaa** [comment]
all previous code is saved in https://github.com/StackStorm/st2-packages/tree/feature/all-packages

**Comment by dennybaa** [comment]
@dzimine would you please ack.

**Comment by dennybaa** [comment]
@lakshmi-kannan @dzimine @armab Guys any objections or suggestions? I would like to merge it sooner.

**Comment by dzimine** [comment]
no objections or input from me other than it should work :)

**Comment by dennybaa** [comment]
awesome, thank you Dmitry. going for it!

**Pull request merged**
