### PR TITLE
Rhel fixes

### PR DESCRIPTION
**Pull request by dennybaa**

### CODE REVIEW

**Comment by dennybaa** [comment]
resolves #73

**Comment by lakshmi-kannan** [comment]
How can I help test this? When you merge, should I just install the bundle and repeat the manual virtualenv creation steps?

**Comment by dennybaa** [comment]
@lakshmi-kannan same procedure actually. Just install stackstorm from el7 bintray repo, following the steps from manas gist from ubuntu. Then run `packs.install`, it should work. For el6 more difficult, you should run `docker-compose run el6` and `docker exec -it st2_packages_centos6test_1 bash` and run `packs.install` from there.

**Comment by lakshmi-kannan** [comment]
Tested this on EL7 and it works. 

```
[vagrant@st2packages ~]$ uname -a
Linux st2packages 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@st2packages ~]$

[vagrant@st2packages ~]$ st2 run packs.install packs=aws
...........
id: 569d7b96d535551614e2bdaa
action.ref: packs.install
status: succeeded
start_timestamp: 2016-01-18T23:56:06.171878Z
end_timestamp: 2016-01-18T23:56:27.105498Z
+--------------------------+-----------+--------------------------+-------------------------+-------------------------------+
| id                       | status    | task                     | action                  | start_timestamp               |
+--------------------------+-----------+--------------------------+-------------------------+-------------------------------+
| 569d7b96d5355515fc63cca0 | succeeded | download                 | packs.download          | Mon, 18 Jan 2016 23:56:06 UTC |
| 569d7b9bd5355515fc63cca3 | succeeded | virtualenv_prerun        | packs.virtualenv_prerun | Mon, 18 Jan 2016 23:56:11 UTC |
| 569d7b9cd5355515fc63cca6 | succeeded | setup_virtualenv         | packs.setup_virtualenv  | Mon, 18 Jan 2016 23:56:12 UTC |
| 569d7ba2d5355515fc63cca9 | succeeded | reload                   | packs.load              | Mon, 18 Jan 2016 23:56:18 UTC |
| 569d7ba9d5355515fc63ccac | succeeded | restart-sensor-container | packs.restart_component | Mon, 18 Jan 2016 23:56:25 UTC |
+--------------------------+-----------+--------------------------+-------------------------+-------------------------------+
[vagrant@st2packages ~]$
```

However, looking at virtualenv_opts in st2.conf file, ``--always-copy`` is not set. Is this intentional for RHEL?

**Comment by lakshmi-kannan** [comment]
@dennybaa Please confirm ^ and then I'll test EL6. I'll also add instructions for RHEL6 to this https://github.com/StackStorm/st2-packages/pull/83 while I do that.

**Comment by dennybaa** [comment]
@lakshmi-kannan, EL7 doesn't require `--always-copy`, it doesn't work with this parameter.
All others including EL6 have it.

**Comment by lakshmi-kannan** [comment]
@dennybaa Will validate EL6 today.

**Pull request merged**
