### PR TITLE
Make sure we also set DEBIAN_FRONTEND environment variable when installing dev version of packages

### PR DESCRIPTION
**Pull request by Kami**
#616 fixed Bionic Build for stable packages (afaik) and I believe this should fix it for dev versions (scenario where we directly wget the package).

### CODE REVIEW

**Comment by Kami** [comment]
Another option would be to just set ``DEBIAN_FRONTEND=noninteractive`` globally. In theory, it shouldn't hurt anything since the whole installer script should be non-interactive anyway.

**Comment by Kami** [comment]
I confirmed it's working by running ``bash st2_bootstrap.sh --force-branch=bionic_fix --staging --unstable --dev=st2/10367 --user=st2admin --password=Ch@ngeMe``.

I will go ahead and merge it to unblock the builds (and also re-run failed executions).

**Comment by Kami** [comment]
I confirmed it fixes installer script timeout issue by re-running the build, but now some other step failed with a different error...

**Comment by armab** [comment]
:+1:

**Pull request merged**
