### PR TITLE
Remove Wheezy and Jessie

### PR DESCRIPTION
**Pull request by armab**
Partial work on https://github.com/StackStorm/st2-packages/issues/365 to remove `wheezy` and `jessie`.

- [x] remove from circle.yml
- [x] other occurencies: readme, docker-compose, etc
- [x] `deb` packaging changes/cleanup
- [x] change parallel `6` -> `4` in CircleCI UI

### CODE REVIEW

**Comment by armab** [comment]
Also updated to use `debhelper` version 10-compatible: https://wiki.debian.org/Teams/pkg-systemd/Packaging which has more systemd-friendly adjustments.

**Comment by Kami** [comment]
I believe this or a related change is causing v2.3 build failure - https://circleci.com/gh/StackStorm/st2-packages/2645

I assume we also need to merge this or some other PR into v2.3?

**Comment by Kami** [comment]
I picked most of the changes from master into v2.3, I believe this should do it.

It was a huge pita to sync up up, since those branches have diverged quite significantly...

**Comment by Kami** [comment]
The issue was actually related to new version of docker-compose - https://github.com/StackStorm/st2-packages/pull/475.

**Pull request merged**
